# Generated by Django 3.2.8 on 2022-08-13 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='cost_per_item',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='last_sales_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity_in_stock',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity_sold',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='stock_date',
        ),
        migrations.AddField(
            model_name='inventory',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='inventory',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
